"use client";

import type { Metadata } from "next";
import "./globals.css";
import { ReactNode } from "react";
import Head from "next/head";
import { ArrowPathRoundedSquareIcon } from "@heroicons/react/24/solid";
import ContractProvider from "@/context/contract";
import AlertProvider from "@/context/alert";

const metadata: Metadata = {
  title: "Collateralized Loans",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en" className="h-full bg-gray-100">
      <Head>
        <title>{metadata.title as string}</title>
        <meta name="description" content={metadata.description as string} />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body className="h-full">
        <AlertProvider>
          <ContractProvider>
            <div className="min-h-full">
              <div className="bg-gray-800 pb-32">
                <header className="py-10">
                  <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
                    <h1 className="text-3xl font-bold tracking-tight text-white text-center">
                      <ArrowPathRoundedSquareIcon className="h-8 w-8 inline-block mr-2" />
                      <span>Collateralized Loans</span>
                    </h1>
                  </div>
                </header>
              </div>
              <main className="-mt-32">{children}</main>
            </div>
          </ContractProvider>
        </AlertProvider>
      </body>
    </html>
  );
}
